### PR TITLE
Use redux-logger

### PR DESCRIPTION
**Pull request by neighborhood999**
Use redux-logger for development and    added semicolon and use ES6 syntax.
I updated production section, because production env don't console any information for user.

### CODE REVIEW

**Comment by StevenIseki** [comment]
Hi thanks for adding to this, however I would ask why do we want to use semi-colons. I am following [standard](https://github.com/feross/standard) styling guide. Also I don't think we want to log to the console in production. Thanks

**Comment by neighborhood999** [comment]
@StevenIseki That's OK. Sorry use semi-colons maybe it's my habit.

**Comment by neighborhood999** [comment]
@StevenIseki I will update this PR. Just add `redux-logger` for console.log.

**Comment by vpanjganj** [comment]
I was just about to suggest `redux-logger` when I saw this PR.

**Comment by StevenIseki** [comment]
new version uses redux logger

**Pull request closed without merging**
